-- MySQL Script generated by MySQL Workbench
-- Mon Jan 20 10:49:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BarcenaCoffee
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BarcenaCoffee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BarcenaCoffee` DEFAULT CHARACTER SET utf8 ;
USE `BarcenaCoffee` ;

-- -----------------------------------------------------
-- Table `BarcenaCoffee`.`Office`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BarcenaCoffee`.`Office` ;

CREATE TABLE IF NOT EXISTS `BarcenaCoffee`.`Office` (
  `OfficeId` CHAR(36) NOT NULL,
  `OfficeName` NVARCHAR(45) NULL,
  PRIMARY KEY (`OfficeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BarcenaCoffee`.`Pantry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BarcenaCoffee`.`Pantry` ;

CREATE TABLE IF NOT EXISTS `BarcenaCoffee`.`Pantry` (
  `PantryId` CHAR(36) NOT NULL,
  `OfficeId` CHAR(36) NOT NULL,
  `PantryName` NVARCHAR(45) NULL,
  `CoffeeBeanUnits` INT UNSIGNED NOT NULL,
  `SugarUnits` INT UNSIGNED NOT NULL,
  `MilkUnits` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`PantryId`),
  INDEX `fk_Pantry_Office1_idx` (`OfficeId` ASC) VISIBLE,
  CONSTRAINT `fk_Pantry_Office`
    FOREIGN KEY (`OfficeId`)
    REFERENCES `BarcenaCoffee`.`Office` (`OfficeId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BarcenaCoffee`.`Drink`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BarcenaCoffee`.`Drink` ;

CREATE TABLE IF NOT EXISTS `BarcenaCoffee`.`Drink` (
  `DrinkId` CHAR(36) NOT NULL,
  `DrinkImageFileName` NVARCHAR(180) NULL,
  `DrinkName` NVARCHAR(45) NULL,
  `CoffeeBeanUnits` INT UNSIGNED NOT NULL,
  `SugarUnits` INT UNSIGNED NOT NULL,
  `MilkUnits` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`DrinkId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BarcenaCoffee`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BarcenaCoffee`.`Order` ;

CREATE TABLE IF NOT EXISTS `BarcenaCoffee`.`Order` (
  `OrderId` CHAR(36) NOT NULL,
  `DrinkId` CHAR(36) NOT NULL,
  `PantryId` CHAR(36) NULL,
  `OrderDate` DATETIME NOT NULL,
  PRIMARY KEY (`OrderId`),
  INDEX `fk_Order_Drink_idx` (`DrinkId` ASC) VISIBLE,
  INDEX `fk_Order_Pantry1_idx` (`PantryId` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Drink`
    FOREIGN KEY (`DrinkId`)
    REFERENCES `BarcenaCoffee`.`Drink` (`DrinkId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Pantry`
    FOREIGN KEY (`PantryId`)
    REFERENCES `BarcenaCoffee`.`Pantry` (`PantryId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `BarcenaCoffee`.`Office`
-- -----------------------------------------------------
START TRANSACTION;
USE `BarcenaCoffee`;
INSERT INTO `BarcenaCoffee`.`Office` (`OfficeId`, `OfficeName`) VALUES ('9572f66d-c411-496f-9d05-efffe2d4e6e8', 'Office A');
INSERT INTO `BarcenaCoffee`.`Office` (`OfficeId`, `OfficeName`) VALUES ('29ffca46-4a18-49fd-b208-4a7bae3317dd', 'Office B');
INSERT INTO `BarcenaCoffee`.`Office` (`OfficeId`, `OfficeName`) VALUES ('afd79660-3b28-4fb4-9094-cb88d5ac3150', 'Office X');

COMMIT;


-- -----------------------------------------------------
-- Data for table `BarcenaCoffee`.`Pantry`
-- -----------------------------------------------------
START TRANSACTION;
USE `BarcenaCoffee`;
INSERT INTO `BarcenaCoffee`.`Pantry` (`PantryId`, `OfficeId`, `PantryName`, `CoffeeBeanUnits`, `SugarUnits`, `MilkUnits`) VALUES ('c6066eb0-53ca-43e1-97aa-3c2169eec659', '9572f66d-c411-496f-9d05-efffe2d4e6e8', 'Pantry A', 45, 45, 45);
INSERT INTO `BarcenaCoffee`.`Pantry` (`PantryId`, `OfficeId`, `PantryName`, `CoffeeBeanUnits`, `SugarUnits`, `MilkUnits`) VALUES ('96a8bf25-ce6d-40e9-93cf-2d62724fb463', '9572f66d-c411-496f-9d05-efffe2d4e6e8', 'Pantry B', 30, 45, 30);
INSERT INTO `BarcenaCoffee`.`Pantry` (`PantryId`, `OfficeId`, `PantryName`, `CoffeeBeanUnits`, `SugarUnits`, `MilkUnits`) VALUES ('04d50500-e716-45ad-9611-31b3c85033fe', '29ffca46-4a18-49fd-b208-4a7bae3317dd', 'Pantry C', 20, 20, 20);
INSERT INTO `BarcenaCoffee`.`Pantry` (`PantryId`, `OfficeId`, `PantryName`, `CoffeeBeanUnits`, `SugarUnits`, `MilkUnits`) VALUES ('9cf13588-8aa6-465c-962d-8b55ca987580', 'afd79660-3b28-4fb4-9094-cb88d5ac3150', 'Pantry V', 30, 30, 30);
INSERT INTO `BarcenaCoffee`.`Pantry` (`PantryId`, `OfficeId`, `PantryName`, `CoffeeBeanUnits`, `SugarUnits`, `MilkUnits`) VALUES ('cb8ffad2-f73d-4f9d-9bc7-64eef8728d2c', 'afd79660-3b28-4fb4-9094-cb88d5ac3150', 'Pantry V2', 25, 25, 25);
INSERT INTO `BarcenaCoffee`.`Pantry` (`PantryId`, `OfficeId`, `PantryName`, `CoffeeBeanUnits`, `SugarUnits`, `MilkUnits`) VALUES ('b9fb9c97-b002-4146-8740-444acb131be4', '9572f66d-c411-496f-9d05-efffe2d4e6e8', 'Pantry X', 20, 20, 20);
INSERT INTO `BarcenaCoffee`.`Pantry` (`PantryId`, `OfficeId`, `PantryName`, `CoffeeBeanUnits`, `SugarUnits`, `MilkUnits`) VALUES ('31f19094-11f7-4d00-b0d1-a11c471ada2d', '9572f66d-c411-496f-9d05-efffe2d4e6e8', 'Pantry Y', 45, 60, 30);
INSERT INTO `BarcenaCoffee`.`Pantry` (`PantryId`, `OfficeId`, `PantryName`, `CoffeeBeanUnits`, `SugarUnits`, `MilkUnits`) VALUES ('50cf913e-5b27-4b37-ad5c-5458de51af5c', '9572f66d-c411-496f-9d05-efffe2d4e6e8', 'Pantry Z', 25, 15, 20);

COMMIT;


-- -----------------------------------------------------
-- Data for table `BarcenaCoffee`.`Drink`
-- -----------------------------------------------------
START TRANSACTION;
USE `BarcenaCoffee`;
INSERT INTO `BarcenaCoffee`.`Drink` (`DrinkId`, `DrinkImageFileName`, `DrinkName`, `CoffeeBeanUnits`, `SugarUnits`, `MilkUnits`) VALUES ('24fd81f8-d58a-4bcc-9f35-dc6cd5641906', 'double-americano.png', 'Double Americano', 3, 0, 0);
INSERT INTO `BarcenaCoffee`.`Drink` (`DrinkId`, `DrinkImageFileName`, `DrinkName`, `CoffeeBeanUnits`, `SugarUnits`, `MilkUnits`) VALUES ('261e1685-cf26-494c-b17c-3546e65f5620', 'sweet-latte.png', 'Sweet Latte', 2, 5, 3);
INSERT INTO `BarcenaCoffee`.`Drink` (`DrinkId`, `DrinkImageFileName`, `DrinkName`, `CoffeeBeanUnits`, `SugarUnits`, `MilkUnits`) VALUES ('f98e4d74-0f68-4aac-89fd-047f1aaca6b6', 'flat-white.png', 'Flat White', 2, 1, 4);

COMMIT;

